###
# Base URL Test
GET https://cse-341-project1-gsq2.onrender.com/

###
# API Documentation Test
GET https://cse-341-project1-gsq2.onrender.com/api-docs/
###
# Contacts API Tests
GET https://cse-341-project1-gsq2.onrender.com/contacts

###
# Get Contact by ID Test
GET https://cse-341-project1-gsq2.onrender.com/contacts/6917a5543a4f44f198086c9f

###
# Create Contact Test
POST https://cse-341-project1-gsq2.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Joshua",
  "lastName": "Banda",
  "email": "joshua.banda@example.com",
  "favoriteColor": "Maroon",
  "birthday": "2005-03-18"
}

###
# Update Contact Test
PUT https://cse-341-project1-gsq2.onrender.com/contacts/6917a5543a4f44f198086c9f
Content-Type: application/json

{
  "firstName": "Kondi",
  "lastName": "Baluwa",
  "email": "kondi.baluwa@example.com",
  "favoriteColor": "Blue",
  "birthday": "2021-10-23"
}

###
# Delete Contact Test
DELETE https://cse-341-project1-gsq2.onrender.com/contacts/64c8b5b5f5b5b5b5b5b5b5b5
